name: route build
on:
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: get Repo
        uses: actions/checkout@v4 

      - name: set GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/route:latest"
          
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          
          echo "──────────────────────────────────────────"
          echo "Image ready: $IMAGE_NAME"
          echo "──────────────────────────────────────────"
